apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: secret
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  encryptedData:
    DATABASE_URL:
    JUDGE0_API_URL:
    REDIS_URL:
  template:
    metadata:
      name: secret
    type: Opaque
